import type { Equipment, MaintenanceTeam, MaintenanceRequest } from "./types"
import { extractFirstNameFromEmail } from "./utils"

export const mockTeams: MaintenanceTeam[] = [
  {
    id: "team-1",
    name: "IT Support",
    description: "Hardware and software maintenance",
    members: [
      {
        id: "tech-1",
        name: extractFirstNameFromEmail("alex@gearguard.com"),
        email: "alex@gearguard.com",
        role: "lead",
        avatar: "/professional-male-technician.jpg",
      },
      {
        id: "tech-2",
        name: extractFirstNameFromEmail("emily@gearguard.com"),
        email: "emily@gearguard.com",
        role: "technician",
        avatar: "/professional-female-technician.jpg",
      },
    ],
    createdAt: "2024-01-15",
  },
  {
    id: "team-2",
    name: "Mechanics",
    description: "Heavy machinery and vehicle maintenance",
    members: [
      {
        id: "tech-3",
        name: extractFirstNameFromEmail("mike@gearguard.com"),
        email: "mike@gearguard.com",
        role: "lead",
        avatar: "/mechanic-worker-male.jpg",
      },
      {
        id: "tech-4",
        name: extractFirstNameFromEmail("lisa@gearguard.com"),
        email: "lisa@gearguard.com",
        role: "technician",
        avatar: "/mechanic-worker-female.jpg",
      },
    ],
    createdAt: "2024-01-15",
  },
  {
    id: "team-3",
    name: "Electricians",
    description: "Electrical systems and power equipment",
    members: [
      {
        id: "tech-5",
        name: extractFirstNameFromEmail("david@gearguard.com"),
        email: "david@gearguard.com",
        role: "lead",
        avatar: "/electrician-worker.jpg",
      },
      {
        id: "tech-6",
        name: extractFirstNameFromEmail("emma@gearguard.com"),
        email: "emma@gearguard.com",
        role: "technician",
        avatar: "/professional-female-electrician.jpg",
      },
    ],
    createdAt: "2024-01-15",
  },
  {
    id: "team-4",
    name: "HVAC Team",
    description: "Heating, ventilation, and air conditioning",
    members: [
      {
        id: "tech-7",
        name: extractFirstNameFromEmail("robert@gearguard.com"),
        email: "robert@gearguard.com",
        role: "lead",
        avatar: "/hvac-technician-male.jpg",
      },
    ],
    createdAt: "2024-02-01",
  },
]

export const mockEquipment: Equipment[] = [
  {
    id: "eq-1",
    name: "CNC Milling Machine",
    serialNumber: "CNC-2024-001",
    purchaseDate: "2023-06-15",
    warrantyExpiry: "2026-06-15",
    location: "Building A - Floor 2",
    department: "Manufacturing",
    defaultTeamId: "team-2",
    defaultTechnicianId: "tech-3",
    isScrap: false,
    failureCount: 3,
    createdAt: "2023-06-15",
    updatedAt: "2024-12-01",
  },
  {
    id: "eq-2",
    name: "Server Rack Unit #12",
    serialNumber: "SRV-2024-012",
    purchaseDate: "2024-01-10",
    warrantyExpiry: "2027-01-10",
    location: "Data Center",
    department: "IT",
    defaultTeamId: "team-1",
    defaultTechnicianId: "tech-1",
    isScrap: false,
    failureCount: 0,
    createdAt: "2024-01-10",
    updatedAt: "2024-11-15",
  },
  {
    id: "eq-3",
    name: "Industrial Air Compressor",
    serialNumber: "IAC-2022-005",
    purchaseDate: "2022-03-20",
    warrantyExpiry: "2025-03-20",
    location: "Building B - Basement",
    department: "Facilities",
    defaultTeamId: "team-2",
    defaultTechnicianId: "tech-4",
    isScrap: false,
    failureCount: 7,
    createdAt: "2022-03-20",
    updatedAt: "2024-12-10",
  },
  {
    id: "eq-4",
    name: "Main Electrical Panel",
    serialNumber: "MEP-2020-001",
    purchaseDate: "2020-08-05",
    warrantyExpiry: "2025-08-05",
    location: "Building A - Ground Floor",
    department: "Facilities",
    defaultTeamId: "team-3",
    defaultTechnicianId: "tech-5",
    isScrap: false,
    failureCount: 1,
    createdAt: "2020-08-05",
    updatedAt: "2024-10-20",
  },
  {
    id: "eq-5",
    name: "Forklift #3",
    serialNumber: "FLT-2021-003",
    purchaseDate: "2021-11-12",
    warrantyExpiry: "2024-11-12",
    location: "Warehouse",
    department: "Logistics",
    defaultTeamId: "team-2",
    defaultTechnicianId: "tech-3",
    isScrap: false,
    failureCount: 5,
    createdAt: "2021-11-12",
    updatedAt: "2024-12-05",
  },
  {
    id: "eq-6",
    name: "HVAC Unit - Zone A",
    serialNumber: "HVAC-2019-001",
    purchaseDate: "2019-04-22",
    warrantyExpiry: "2024-04-22",
    location: "Building A - Roof",
    department: "Facilities",
    defaultTeamId: "team-4",
    defaultTechnicianId: "tech-7",
    isScrap: false,
    failureCount: 4,
    createdAt: "2019-04-22",
    updatedAt: "2024-11-28",
  },
]

export const mockRequests: MaintenanceRequest[] = [
  {
    id: "req-1",
    subject: "CNC spindle vibration issue",
    description: "Unusual vibration detected during high-speed operations",
    type: "corrective",
    equipmentId: "eq-1",
    equipmentName: "CNC Milling Machine",
    teamId: "team-2",
    teamName: "Mechanics",
    technicianId: "tech-3",
    technicianName: extractFirstNameFromEmail("mike@gearguard.com"),
    technicianAvatar: "/mechanic-worker-male.jpg",
    location: "Building A - Floor 2",
    scheduledDate: "2025-01-15",
    dueDate: "2025-01-15",
    status: "new",
    createdBy: "user-1",
    createdByName: extractFirstNameFromEmail("john@gearguard.com"),
    createdAt: "2025-01-10",
    updatedAt: "2025-01-10",
  },
  {
    id: "req-2",
    subject: "Server cooling fan replacement",
    description: "Preventive replacement of aging cooling fans",
    type: "preventive",
    equipmentId: "eq-2",
    equipmentName: "Server Rack Unit #12",
    teamId: "team-1",
    teamName: "IT Support",
    technicianId: "tech-1",
    technicianName: extractFirstNameFromEmail("alex@gearguard.com"),
    technicianAvatar: "/professional-male-technician.jpg",
    location: "Data Center",
    scheduledDate: "2025-01-20",
    dueDate: "2025-01-20",
    duration: 2,
    status: "in-progress",
    createdBy: "user-2",
    createdByName: extractFirstNameFromEmail("sarah@gearguard.com"),
    createdAt: "2025-01-05",
    updatedAt: "2025-01-12",
  },
  {
    id: "req-3",
    subject: "Compressor pressure drop",
    description: "System not maintaining required pressure levels",
    type: "corrective",
    equipmentId: "eq-3",
    equipmentName: "Industrial Air Compressor",
    teamId: "team-2",
    teamName: "Mechanics",
    technicianId: "tech-4",
    technicianName: extractFirstNameFromEmail("lisa@gearguard.com"),
    technicianAvatar: "/mechanic-worker-female.jpg",
    location: "Building B - Basement",
    scheduledDate: "2025-01-18",
    dueDate: "2025-01-18",
    duration: 4,
    status: "in-progress",
    createdBy: "user-1",
    createdByName: extractFirstNameFromEmail("john@gearguard.com"),
    createdAt: "2025-01-08",
    updatedAt: "2025-01-12",
  },
  {
    id: "req-4",
    subject: "Monthly electrical inspection",
    description: "Routine monthly inspection of main panel",
    type: "preventive",
    equipmentId: "eq-4",
    equipmentName: "Main Electrical Panel",
    teamId: "team-3",
    teamName: "Electricians",
    technicianId: "tech-5",
    technicianName: extractFirstNameFromEmail("david@gearguard.com"),
    technicianAvatar: "/electrician-worker.jpg",
    location: "Building A - Ground Floor",
    scheduledDate: "2025-02-05",
    dueDate: "2025-02-05",
    status: "new",
    createdBy: "user-3",
    createdByName: extractFirstNameFromEmail("mike@gearguard.com"),
    createdAt: "2025-01-15",
    updatedAt: "2025-01-15",
  },
  {
    id: "req-5",
    subject: "Forklift hydraulic leak",
    description: "Oil leak detected in hydraulic system",
    type: "corrective",
    equipmentId: "eq-5",
    equipmentName: "Forklift #3",
    teamId: "team-2",
    teamName: "Mechanics",
    technicianId: "tech-3",
    technicianName: extractFirstNameFromEmail("mike@gearguard.com"),
    technicianAvatar: "/mechanic-worker-male.jpg",
    location: "Warehouse",
    scheduledDate: "2025-01-10",
    dueDate: "2025-01-10",
    duration: 6,
    status: "repaired",
    createdBy: "user-2",
    createdByName: extractFirstNameFromEmail("sarah@gearguard.com"),
    createdAt: "2025-01-05",
    updatedAt: "2025-01-10",
  },
  {
    id: "req-6",
    subject: "HVAC filter replacement",
    description: "Quarterly filter replacement and system check",
    type: "preventive",
    equipmentId: "eq-6",
    equipmentName: "HVAC Unit - Zone A",
    teamId: "team-4",
    teamName: "HVAC Team",
    technicianId: "tech-7",
    technicianName: extractFirstNameFromEmail("robert@gearguard.com"),
    technicianAvatar: "/hvac-technician-male.jpg",
    location: "Building A - Roof",
    scheduledDate: "2025-02-15",
    dueDate: "2025-02-15",
    status: "new",
    createdBy: "user-1",
    createdByName: extractFirstNameFromEmail("john@gearguard.com"),
    createdAt: "2025-01-10",
    updatedAt: "2025-01-10",
  },
  {
    id: "req-7",
    subject: "Emergency compressor shutdown",
    description: "Complete system failure - unit beyond repair",
    type: "corrective",
    equipmentId: "eq-3",
    equipmentName: "Industrial Air Compressor",
    teamId: "team-2",
    teamName: "Mechanics",
    technicianId: "tech-4",
    technicianName: extractFirstNameFromEmail("lisa@gearguard.com"),
    technicianAvatar: "/mechanic-worker-female.jpg",
    location: "Building B - Basement",
    scheduledDate: "2025-01-05",
    dueDate: "2025-01-05",
    duration: 8,
    status: "repaired",
    createdBy: "user-2",
    createdByName: extractFirstNameFromEmail("sarah@gearguard.com"),
    createdAt: "2025-01-02",
    updatedAt: "2025-01-05",
  },
]
